feat(containers): add Linuxbrew to the Dockerfile + add an new directory for sourcing stuff in ~/.bashrc_d
Also added our Docker ignore file to ensure READMEs aren't
included tho. Also abit of updates on Cloudflared installer
scripts btw.

Signed-off-by: Andrei Jiroh Eugenio Halili <andreijiroh@madebythepins.tk>

diff --git a/toolkits/packages/scripts/cloudflare-updater b/toolkits/packages/scripts/cloudflare-updater
--- a/toolkits/packages/scripts/cloudflare-updater
+++ b/toolkits/packages/scripts/cloudflare-updater
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 echo "[toolkit-scripts] Installing Argo Tunnel agent"
-/home/coder/.local/bin/cloudflared-updater
-echo "[toolkit-scripts] Installer script exited with $?, please bug the image maintainers"
-echo "[toolkit-scripts] if the exit code isn't zero."
 
+if ! /home/coder/.local/bin/cloudflared-updater; then
+  echo "[tooklit-scripts] Failed to install/update Cloudflared. Please bug the image maintainers if symptoms presists."
+  exit 1
+fi
diff --git a/toolkits/packages/scripts/cloudflared-updater b/toolkits/packages/scripts/cloudflared-updater
--- a/toolkits/packages/scripts/cloudflared-updater
+++ b/toolkits/packages/scripts/cloudflared-updater
@@ -7,6 +7,11 @@
 # pull the builder's arch first
 ARCH_TO_USE="$IMAGE_ARCH"
 
+wgetFailExit(){
+  EXIT_CODE=$?
+  echo "[cloudflared-updater] Install script failed to download the binary file with exit code ${EDIT_CODE}" && exit "$EDIT_CODE"
+}
+
 if [[ $ARCH_TO_USE == "" ]]; then
   ARCH_TO_USE="$(uname -p)"
 fi
@@ -20,15 +25,17 @@ CLOUDFLARED_VERSION=$(curl --silent "https://api.github.com/repos/cloudflare/clo
 
 echo "[cloudflared-updater] Installing latest version of Argo Tunnel agent.."
 if [[ $ARCH_TO_USE == "aarch64" ]]; then
-  sudo wget https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-arm64 -O /usr/local/bin/cloudflared
+  if ! sudo wget --fail https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-arm64 -O /usr/local/bin/cloudflared; then
+     wgetFailedExit
+  else
+     true
+  fi
 else
-  sudo wget https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared
+  if ! sudo wget --fail https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared; then
+     wgetFailedExit
+  else
+     true
+  fi;
 fi
-sudo chmod +x /usr/local/bin/cloudflared
 
-if [[ $? == "0" ]]; then
-  echo "[cloudflared-installer] Successfully updated!"
-else
-  echo "[cloudlfared-installer] Installer failed, exiting..."
-  exit $?
-fi
+sudo chmod +x /usr/local/bin/cloudflared
