chore(toolkits-packages:scripts): fix any potential issues found by Shellcheck
Signed-off-by: Andrei Jiroh Eugenio Halili <andreijiroh@madebythepins.tk>

diff --git a/toolkits/packages/scripts/cloudflared-updater b/toolkits/packages/scripts/cloudflared-updater
--- a/toolkits/packages/scripts/cloudflared-updater
+++ b/toolkits/packages/scripts/cloudflared-updater
@@ -9,7 +9,7 @@ ARCH_TO_USE="$IMAGE_ARCH"
 
 wgetFailExit(){
   EXIT_CODE=$?
-  echo "[cloudflared-updater] Install script failed to download the binary file with exit code ${EDIT_CODE}" && exit "$EDIT_CODE"
+  echo "[cloudflared-updater] Install script failed to download the binary file with exit code ${EXIT_CODE}" && exit "$EXIT_CODE"
 }
 
 if [[ $ARCH_TO_USE == "" ]]; then
@@ -25,13 +25,13 @@ CLOUDFLARED_VERSION=$(curl --silent "https://api.github.com/repos/cloudflare/clo
 
 echo "[cloudflared-updater] Installing latest version of Argo Tunnel agent.."
 if [[ $ARCH_TO_USE == "aarch64" ]]; then
-  if ! sudo wget --fail https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-arm64 -O /usr/local/bin/cloudflared; then
+  if ! sudo wget --fail "https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-arm64" -O /usr/local/bin/cloudflared; then
      wgetFailedExit
   else
      true
   fi
 else
-  if ! sudo wget --fail https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared; then
+  if ! sudo wget --fail "https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-amd64" -O /usr/local/bin/cloudflared; then
      wgetFailedExit
   else
      true
