fix(dockerfile): Finally make this image both amd64 and arm64 compartible in one build
Todo: This will need to be tested first.

Signed-off-by: Andrei Jiroh Eugenio Halili <andreijiroh@madebythepins.tk>

diff --git a/toolkits/packages/scripts/cloudflared-updater b/toolkits/packages/scripts/cloudflared-updater
--- a/toolkits/packages/scripts/cloudflared-updater
+++ b/toolkits/packages/scripts/cloudflared-updater
@@ -5,4 +5,27 @@
 # during image build btw
 
 # pull the builder's arch first
-ARCH_TO_USE=$IMAGE_ARCH_TO_USE
+ARCH_TO_USE="$IMAGE_ARCH"
+
+if [[ $ARCH_TO_USE == "" ]]; then
+  ARCH_TO_USE="$(uname -p)"
+fi
+
+if [[ -f /usr/local/bin/cloudflared ]]; then
+  echo "[cloudlfared-updater] Removing old version..."
+  sudo rm -fv /usr/local/bin/cloudflared
+fi
+
+echo "[cloudflared-updater] Installing latest version of Argo Tunnel agent.."
+if [[ $ARCH_TO_USE == "arm64" ]]; then
+  sudo wget https://github.com/cloudflare/cloudflared/releases/download/2021.4.0/cloudflared-linux-arm64 -O /usr/local/bin/cloudflared
+else
+  sudo wget https://github.com/cloudflare/cloudflared/releases/download/latest/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared
+fi
+
+if [[ $? == "0" ]]; then
+  echo "[cloudflared-installer] Successfully updated!"
+else
+  echo "[cloudlfared-installer] Installer failed, exiting..."
+  exit $?
+fi
